export const MULTICENTER_DATASET_VISIBLE_STATUS = {
    PUBLIC: "PUBLIC",
    PRIVATE: "PRIVATE",
};

export const MULTICENTER_ACCESS_REQUEST_STATUS = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
};

export const MULTICENTER_GRANT_STATUS = {
    GRANTED: "GRANTED",
    REVOKED: "REVOKED",
};

